【Fixed】応募画面のバックエンド実装
mysthkr/medi_app pull request #6
Opened 2024-02-12 15:51 UTC by DaisukeKurita

close #2 

## バリデーションの設定
- [x] 未入力をはじく
- [x] メールアドレスの正規表現を設定
- [x] 電話番号の正規表現を設定（ハイフンなし、携帯電話番号として設定）
- [x]  パスワードの文字数制限

## 国際化
- [x] 国際化
- [x] tailwindcss-railsの設定

## データベースの設定
- [x] config/database.ymlを、.gitignoreに追加

2024-02-13 07:10 UTC, mysthkr requested changes
応募画面のパスワードの項目は削除でお願いいたします。

2024-02-13 07:10 UTC, mysthkr commented on app/models/candidate.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
応募画面はユーザー登録とは別物にしたいので
パスワードの項目は削除するようにお願いいたします。

2024-02-13 07:10 UTC, mysthkr commented on config/locales/model.ja.yml
> +        password: パスワード
こちらもパスワードを削除お願いいたします。

2024-02-18 15:22 UTC, DaisukeKurita commented on app/models/candidate.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
@mysthkr 
作業完了しました！

2024-02-18 15:22 UTC, DaisukeKurita commented on config/locales/model.ja.yml
> +        password: パスワード
@mysthkr 
作業完了しました！

2024-02-18 15:23 UTC, merged